<?php

/**
 * Basebadges
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $badges_id
 * @property integer $status
 * @property users $users
 * 
 * @method integer getUserId()    Returns the current record's "user_id" value
 * @method integer getBadgesId()  Returns the current record's "badges_id" value
 * @method integer getStatus()    Returns the current record's "status" value
 * @method users   getUsers()     Returns the current record's "users" value
 * @method badges  setUserId()    Sets the current record's "user_id" value
 * @method badges  setBadgesId()  Sets the current record's "badges_id" value
 * @method badges  setStatus()    Sets the current record's "status" value
 * @method badges  setUsers()     Sets the current record's "users" value
 * 
 * @package    posting
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basebadges extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('badges');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('badges_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('users', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}