<?php

/**
 * Baselogin_history
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $user_ip
 * @property integer $status
 * @property users $users
 * 
 * @method integer       getUserId()  Returns the current record's "user_id" value
 * @method string        getUserIp()  Returns the current record's "user_ip" value
 * @method integer       getStatus()  Returns the current record's "status" value
 * @method users         getUsers()   Returns the current record's "users" value
 * @method login_history setUserId()  Sets the current record's "user_id" value
 * @method login_history setUserIp()  Sets the current record's "user_ip" value
 * @method login_history setStatus()  Sets the current record's "status" value
 * @method login_history setUsers()   Sets the current record's "users" value
 * 
 * @package    posting
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baselogin_history extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('login_history');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_ip', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('users', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}