<?php

/**
 * Basereviews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $author_id
 * @property integer $recepient_id
 * @property string $text
 * @property boolean $type
 * @property integer $status
 * @property users $users
 * 
 * @method integer getAuthorId()     Returns the current record's "author_id" value
 * @method integer getRecepientId()  Returns the current record's "recepient_id" value
 * @method string  getText()         Returns the current record's "text" value
 * @method boolean getType()         Returns the current record's "type" value
 * @method integer getStatus()       Returns the current record's "status" value
 * @method users   getUsers()        Returns the current record's "users" value
 * @method reviews setAuthorId()     Sets the current record's "author_id" value
 * @method reviews setRecepientId()  Sets the current record's "recepient_id" value
 * @method reviews setText()         Sets the current record's "text" value
 * @method reviews setType()         Sets the current record's "type" value
 * @method reviews setStatus()       Sets the current record's "status" value
 * @method reviews setUsers()        Sets the current record's "users" value
 * 
 * @package    posting
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basereviews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reviews');
        $this->hasColumn('author_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('recepient_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('text', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('type', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('users', array(
             'local' => 'recepient_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}