<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/01/03 09:20:06

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=posting',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
