<?php

/**
 * badgesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class badgesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object badgesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('badges');
    }
}