<?php

/**
 * bidsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class bidsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object bidsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('bids');
    }
}