<?php

/**
 * login_historyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class login_historyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object login_historyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('login_history');
    }
}