<?php

/**
 * paymentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class paymentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object paymentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('payments');
    }
}