<?php

/**
 * projectsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class projectsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object projectsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('projects');
    }
}