<?php

/**
 * projectsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class projectsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object projectsTable
     */
	public function getActiveProjects($per_page = 2)
	{
		$q = $this->createQuery('p')
			->where('p.status <> 0')
			->limit($per_page);

		return $q->execute();
	}
    //public static function getInstance()
    //{
    //    return Doctrine_Core::getTable('projects');
    //}
}