<?php

/**
 * reviewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class reviewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object reviewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('reviews');
    }
}