<?php

/**
 * search_historyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class search_historyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object search_historyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('search_history');
    }
}