<?php

/**
 * usersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class usersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object usersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('users');
    }
}